### ISSUE TITLE
Periodic issue with json decoder in 0.0.3.

### ISSUE THREAD

**Issue by noenfugler** [dcferreira/pylemmy#10]
Traceback (most recent call last):
  File "/Users/noenfugler/PycharmProjects/LemmyModBot/venv/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/PycharmProjects/LemmyModBot/posts_bot.py", line 62, in <module>
    for post in community.stream.get_posts():
  File "/Users/noenfugler/PycharmProjects/LemmyModBot/venv/lib/python3.9/site-packages/pylemmy/utils.py", line 39, in stream_generator
    results = function(**function_kwargs)
  File "/Users/noenfugler/PycharmProjects/LemmyModBot/venv/lib/python3.9/site-packages/pylemmy/models/community.py", line 58, in get_posts
    result = self.lemmy.get_request(LemmyAPI.GetPosts, params=payload)
  File "/Users/noenfugler/PycharmProjects/LemmyModBot/venv/lib/python3.9/site-packages/pylemmy/lemmy.py", line 238, in get_request
    return response.json()
  File "/Users/noenfugler/PycharmProjects/LemmyModBot/venv/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Process finished with exit code 1

**Comment by dcferreira** [comment]
It sounds like something went wrong with the request.
I can't really fix it without more details.
If you find a reproducible example, please let me know.

But for a future release I should add better error handling here, so it's
easier to figure out what went wrong.

**Comment by noenfugler** [comment]
No longer occurring.
