### ISSUE TITLE
'error': 'couldn't create report' in post.py

### ISSUE THREAD

**Issue by noenfugler** [dcferreira/pylemmy#12]
Reproducible sample:

lemmy.world - post id 507787

When attempting to create
Traceback (most recent call last):
  File "/Users/noenfugler/PycharmProjects/LemmyModBot/posts_bot.py", line 65, in <module>
    process_post(post)
  File "/Users/noenfugler/PycharmProjects/LemmyModBot/posts_bot.py", line 51, in process_post
    post.create_report(reason=', '.join(flags))
  File "/Users/noenfugler/PycharmProjects/LemmyModBot/venv/lib/python3.9/site-packages/pylemmy/models/post.py", line 122, in create_report
    parsed_result = api.post.PostReportResponse(**result)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PostReportResponse
post_report_view
  field required (type=value_error.missing)

Process finished with exit code 1

**Comment by noenfugler** [comment]
The error seems to be line 121 of post.py

Here's my payload (redacted auth key):
CreatePostReport(auth='***my_auth_key***', post_id=507787, reason='toxicity, obscene')

Here's the result:
{'error': 'couldnt_create_report'}

Line 122 then fails.

**Comment by noenfugler** [comment]
Instance: lemmy.world
Community: asklemmy
Post name: 'How do I disable autorefresh of the All Communities?'

**Comment by noenfugler** [comment]
Looks like I can bring up the report dialogue through the web frontend, but I don't want to actually create the report in case it changes things.

**Comment by noenfugler** [comment]
Also post_id  497509
Instance: lemmy.world
Community: asklemmy
Post name (title): "“The loudest voice in the room is usually the dumbest” what's an example of this that you have witnessed?"

**Comment by noenfugler** [comment]
I wonder if this error occurs when a report has been previously created by this user for this post/comment.  I'll test.

**Comment by noenfugler** [comment]
I think this has been fixed in Pull Request #15 .
