### ISSUE TITLE
ModuleNotFoundError: No module named 'mypy_extensions' when using lemmy.multi_communities_stream in 0.0.4

### ISSUE THREAD

**Issue by noenfugler** [dcferreira/pylemmy#9]
Might be a packaging issue?  I'm sorry I still have to learn about python packaging.

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/noenfugler/PycharmProjects/LemmyModBot/venv/lib/python3.9/site-packages/pylemmy/__init__.py", line 1, in <module>
    from pylemmy.lemmy import Lemmy  # noqa
  File "/Users/noenfugler/PycharmProjects/LemmyModBot/venv/lib/python3.9/site-packages/pylemmy/lemmy.py", line 11, in <module>
    from pylemmy.models.community import Community, MultiCommunityStream
  File "/Users/noenfugler/PycharmProjects/LemmyModBot/venv/lib/python3.9/site-packages/pylemmy/models/__init__.py", line 1, in <module>
    from pylemmy.models import comment, community, post  # noqa
  File "/Users/noenfugler/PycharmProjects/LemmyModBot/venv/lib/python3.9/site-packages/pylemmy/models/community.py", line 4, in <module>
    from mypy_extensions import KwArg
ModuleNotFoundError: No module named 'mypy_extensions'
python-BaseException

Process finished with exit code 1

**Comment by dcferreira** [comment]
Oops, that's my bad, I forgot to add it to the dependencies.
As a fix you can just add 'mypy-extensions' to your dependencies (e.g. `pip
install mypy-extensions`).

I will fix this on the next release.

**Comment by dcferreira** [comment]
This was fixed I think in 0.0.5.
